### ISSUE TITLE
Error while generating data for BloodHound (Resolved)

### ISSUE THREAD

**Issue by NikushaKalatozi** [BloodHoundAD/BloodHound-Tools#27]
I just downloaded fresh new Kali Virtual Machine (VM) 

Installed Bloodhound and decided to generate some data to play with it.

the following command (**dbconfig, connect, setnodes , setdomain** works perfectly) but command such as (**clear_and_generate, cleardb, generate**) doesn't works and it throws this error.

```
┌──(root💀kali)-[/home/kali/BloodHound_DB_Generator/BloodHound-Tools/DBCreator]
└─# python3 DBCreator.py                                                                                 1 ⨯
================================================================
BloodHound Sample Database Creator
================================================================

Documented commands (type help <topic>):
========================================
clear_and_generate  connect   exit      help       setnodes
cleardb             dbconfig  generate  setdomain

(Cmd) dbconfig
Current Settings:
DB Url: bolt://localhost:7687
DB Username: neo4j
DB Password: neo4jj
Use encryption: False

Enter DB URL [bolt://localhost:7687] 
Enter DB Username [neo4j] 
Enter DB Password [neo4jj] password
Use encryption? y/N n

New Settings:
DB Url: bolt://localhost:7687
DB Username: neo4j
DB Password: password
Use encryption: False

Testing DB Connection
Database Connection Successful!
(Cmd) cleardb
Clearing Database
Resetting Schema
Traceback (most recent call last):
  File "/home/kali/BloodHound_DB_Generator/BloodHound-Tools/DBCreator/DBCreator.py", line 806, in <module>
    MainMenu().cmdloop()
  File "/home/kali/BloodHound_DB_Generator/BloodHound-Tools/DBCreator/DBCreator.py", line 69, in cmdloop
    cmd.Cmd.cmdloop(self)
  File "/usr/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/kali/BloodHound_DB_Generator/BloodHound-Tools/DBCreator/DBCreator.py", line 172, in do_cleardb
    for constraint in session.run("CALL db.constraints"):
  File "/usr/lib/python3/dist-packages/neo4j/__init__.py", line 503, in run
    self._connection.fetch()
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.ClientError: Supplied bookmark [FB:kcwQ2pBhTb3xSHGSufncKQOQBUmQ] does not conform to pattern neo4j:bookmark:v1:tx
```

**Comment by RedTeamMagic** [comment]
> I just downloaded fresh new Kali Virtual Machine (VM)
> 
> Installed Bloodhound and decided to generate some data to play with it.
> 
> the following command (**dbconfig, connect, setnodes , setdomain** works perfectly) but command such as (**clear_and_generate, cleardb, generate**) doesn't works and it throws this error.
> 
> ```
> ┌──(root💀kali)-[/home/kali/BloodHound_DB_Generator/BloodHound-Tools/DBCreator]
> └─# python3 DBCreator.py                                                                                 1 ⨯
> ================================================================
> BloodHound Sample Database Creator
> ================================================================
> 
> Documented commands (type help <topic>):
> ========================================
> clear_and_generate  connect   exit      help       setnodes
> cleardb             dbconfig  generate  setdomain
> 
> (Cmd) dbconfig
> Current Settings:
> DB Url: bolt://localhost:7687
> DB Username: neo4j
> DB Password: neo4jj
> Use encryption: False
> 
> Enter DB URL [bolt://localhost:7687] 
> Enter DB Username [neo4j] 
> Enter DB Password [neo4jj] password
> Use encryption? y/N n
> 
> New Settings:
> DB Url: bolt://localhost:7687
> DB Username: neo4j
> DB Password: password
> Use encryption: False
> 
> Testing DB Connection
> Database Connection Successful!
> (Cmd) cleardb
> Clearing Database
> Resetting Schema
> Traceback (most recent call last):
>   File "/home/kali/BloodHound_DB_Generator/BloodHound-Tools/DBCreator/DBCreator.py", line 806, in <module>
>     MainMenu().cmdloop()
>   File "/home/kali/BloodHound_DB_Generator/BloodHound-Tools/DBCreator/DBCreator.py", line 69, in cmdloop
>     cmd.Cmd.cmdloop(self)
>   File "/usr/lib/python3.9/cmd.py", line 138, in cmdloop
>     stop = self.onecmd(line)
>   File "/usr/lib/python3.9/cmd.py", line 217, in onecmd
>     return func(arg)
>   File "/home/kali/BloodHound_DB_Generator/BloodHound-Tools/DBCreator/DBCreator.py", line 172, in do_cleardb
>     for constraint in session.run("CALL db.constraints"):
>   File "/usr/lib/python3/dist-packages/neo4j/__init__.py", line 503, in run
>     self._connection.fetch()
>   File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 419, in fetch
>     return self._fetch()
>   File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 461, in _fetch
>     response.on_failure(summary_metadata or {})
>   File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 755, in on_failure
>     raise CypherError.hydrate(**metadata)
> neobolt.exceptions.ClientError: Supplied bookmark [FB:kcwQ2pBhTb3xSHGSufncKQOQBUmQ] does not conform to pattern neo4j:bookmark:v1:tx
> ```

Any luck with this? Experiencing errors as well

**Comment by Corkster919** [comment]
[DBCreator_update.zip](https://github.com/BloodHoundAD/BloodHound-Tools/files/6327196/DBCreator_update.zip)

Update the python3 libs to the latest dist-packages with apt-get

Replace the DBCreator.py file with the one attached here to integrate neo4j and python version updates as of today (04/16/2021)

**Comment by NikushaKalatozi** [comment]
I'll try it , thanks for feedback, if something will go wrong I'll update on this thread.

**Comment by NikushaKalatozi** [comment]
> [DBCreator_update.zip](https://github.com/BloodHoundAD/BloodHound-Tools/files/6327196/DBCreator_update.zip)
> 
> Update the python3 libs to the latest dist-packages with apt-get
> 
> Replace the DBCreator.py file with the one attached here to integrate neo4j and python version updates as of today (04/16/2021)

Thank you , I updated all python libraries and now it works!

**Comment by AkamiKuran** [comment]
May I know how to "Update the python3 libs to the latest dist-packages with apt-get"?
